-- AIDo 5.0 数据库结构
-- 约定：人、会话用可读的文本主键（与前端路由 /chat/c1 一致）；消息、TODO 等高频数据用自增 bigint。
-- 所有「属于某个人」的数据都带 owner_id，便于以后接入登录后按用户隔离。

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- —— 人 ——
CREATE TABLE app_user (
  id          text PRIMARY KEY,
  name        text NOT NULL,
  role        text NOT NULL DEFAULT '',
  dept        text NOT NULL DEFAULT '',
  color       text NOT NULL DEFAULT '#94a3b8',
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- 个人偏好：主题、小雀形象、是否允许小雀从日常工作中学习
CREATE TABLE user_preference (
  user_id           text PRIMARY KEY REFERENCES app_user (id) ON DELETE CASCADE,
  theme             text NOT NULL DEFAULT 'system' CHECK (theme IN ('light', 'dark', 'system')),
  agent_look        jsonb NOT NULL DEFAULT '{"preset": "aurora", "custom": null, "glasses": false}',
  memory_learning   boolean NOT NULL DEFAULT true,
  updated_at        timestamptz NOT NULL DEFAULT now()
);

-- —— 会话与消息 ——
CREATE TABLE conversation (
  id               text PRIMARY KEY,
  type             text NOT NULL CHECK (type IN ('dm', 'group')),
  name             text,                       -- 群名；私聊为空，显示对方名字
  color            text,
  member_count     integer NOT NULL DEFAULT 2,  -- 群人数（含未入库的外部成员）
  last_message_at  timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  CHECK (type = 'dm' OR name IS NOT NULL)
);

-- 成员及其个人视角的会话状态：置顶、免打扰、未读、小雀标记
CREATE TABLE conversation_member (
  conversation_id  text NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
  user_id          text NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  pinned           boolean NOT NULL DEFAULT false,
  muted            boolean NOT NULL DEFAULT false,
  unread_count     integer NOT NULL DEFAULT 0 CHECK (unread_count >= 0),
  agent_flag       text,                        -- 小雀精选标记，如「有人 @你」「待回复」
  last_read_at     timestamptz,
  joined_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (conversation_id, user_id)
);
CREATE INDEX conversation_member_user_idx ON conversation_member (user_id);

CREATE TABLE message (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id   text NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
  sender_id         text NOT NULL REFERENCES app_user (id),
  body              text,
  attachment_name   text,
  attachment_size   bigint,                     -- 字节
  sent_at           timestamptz NOT NULL DEFAULT now(),
  CHECK (body IS NOT NULL OR attachment_name IS NOT NULL)
);
CREATE INDEX message_conversation_idx ON message (conversation_id, sent_at DESC, id DESC);
CREATE INDEX message_body_trgm_idx ON message USING gin (body gin_trgm_ops);
CREATE INDEX message_attachment_trgm_idx ON message USING gin (attachment_name gin_trgm_ops)
  WHERE attachment_name IS NOT NULL;

-- 消息里 @ 到的人
CREATE TABLE message_mention (
  message_id  bigint NOT NULL REFERENCES message (id) ON DELETE CASCADE,
  user_id     text NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  PRIMARY KEY (message_id, user_id)
);
CREATE INDEX message_mention_user_idx ON message_mention (user_id);

-- 小雀对会话的未读摘要（按人生成）
CREATE TABLE conversation_summary (
  conversation_id  text NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
  owner_id         text NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  message_count    integer NOT NULL,
  points           text[] NOT NULL,
  generated_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (conversation_id, owner_id)
);

-- 小雀给出的回复建议：quick 为输入框上方的快捷回复，draft 为按你语气起草的整段回复
CREATE TABLE reply_suggestion (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id  text REFERENCES conversation (id) ON DELETE CASCADE,  -- 为空表示通用兜底
  owner_id         text NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  kind             text NOT NULL CHECK (kind IN ('quick', 'draft')),
  body             text NOT NULL,
  position         integer NOT NULL DEFAULT 0
);
CREATE INDEX reply_suggestion_conv_idx ON reply_suggestion (owner_id, conversation_id, kind, position);

-- —— TODO ——
-- status: suggested 小雀建议待确认 | open 待办 | done 已完成 | dismissed 已忽略
CREATE TABLE todo (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id            text NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  title               text NOT NULL CHECK (length(title) BETWEEN 1 AND 200),
  status              text NOT NULL DEFAULT 'open' CHECK (status IN ('suggested', 'open', 'done', 'dismissed')),
  kind                text NOT NULL DEFAULT 'task' CHECK (kind IN ('task', 'reply')),  -- reply：需要回复某个会话
  priority            text CHECK (priority IN ('P0', 'P1', 'P2')),
  planned_date        date,                      -- 计划在哪天做；等于今天即出现在「今天」分组
  due_label           text,                      -- 截止时间的展示文案，如「14:00 前」「明天」
  due_at              timestamptz,               -- 可解析时的精确截止时间
  note                text,                      -- 小雀说明为什么建议这一项
  source_message_id   bigint REFERENCES message (id) ON DELETE SET NULL,
  created_by          text NOT NULL DEFAULT 'user' CHECK (created_by IN ('user', 'agent')),
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  completed_at        timestamptz
);
CREATE INDEX todo_owner_status_idx ON todo (owner_id, status);
CREATE INDEX todo_source_idx ON todo (source_message_id) WHERE source_message_id IS NOT NULL;
CREATE INDEX todo_title_trgm_idx ON todo USING gin (title gin_trgm_ops);

-- 小雀从消息里识别出、但还没放进 TODO 的候选事项；「重新整理」时逐条转为待确认
CREATE TABLE todo_candidate (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id           text NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  title              text NOT NULL,
  priority           text CHECK (priority IN ('P0', 'P1', 'P2')),
  planned_date       date,
  due_label          text,
  note               text,
  source_message_id  bigint REFERENCES message (id) ON DELETE SET NULL,
  found_at           timestamptz NOT NULL DEFAULT now(),
  promoted_todo_id   bigint REFERENCES todo (id) ON DELETE SET NULL
);
CREATE INDEX todo_candidate_pending_idx ON todo_candidate (owner_id, found_at) WHERE promoted_todo_id IS NULL;

-- —— 日程 ——
CREATE TABLE calendar_event (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id    text NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  title       text NOT NULL,
  place       text NOT NULL DEFAULT '',
  starts_at   timestamptz NOT NULL,
  ends_at     timestamptz,
  agent_note  text,                              -- 小雀为这场日程准备的提示
  CHECK (ends_at IS NULL OR ends_at >= starts_at)
);
CREATE INDEX calendar_event_owner_idx ON calendar_event (owner_id, starts_at);

-- —— 记忆 ——
CREATE TABLE memory_profile_tag (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id    text NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  group_name  text NOT NULL,                     -- 工作角色 / 常合作的人 / 工作习惯
  tag         text NOT NULL,
  position    integer NOT NULL DEFAULT 0,
  UNIQUE (owner_id, group_name, tag)
);

CREATE TABLE memory_item (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id    text NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  body        text NOT NULL CHECK (length(body) BETWEEN 1 AND 500),
  source      text NOT NULL DEFAULT '你手动添加',  -- 这条记忆从哪来
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX memory_item_owner_idx ON memory_item (owner_id, created_at DESC);

-- 小雀可以从哪些来源学习
CREATE TABLE memory_source (
  owner_id     text NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  key          text NOT NULL,
  label        text NOT NULL,
  description  text NOT NULL DEFAULT '',
  enabled      boolean NOT NULL DEFAULT true,
  position     integer NOT NULL DEFAULT 0,
  PRIMARY KEY (owner_id, key)
);

-- —— 小雀 ——
-- 自动化能力开关
CREATE TABLE agent_capability (
  owner_id     text NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  key          text NOT NULL,
  title        text NOT NULL,
  description  text NOT NULL DEFAULT '',
  enabled      boolean NOT NULL DEFAULT true,
  position     integer NOT NULL DEFAULT 0,
  PRIMARY KEY (owner_id, key)
);

-- 小雀面板的对话流。不同类型的卡片字段差异大，内容放在 payload（jsonb）：
--   status   { text }
--   user     { text, context }
--   agent    { paragraphs[], bullets[{strong,text,link}], tail }
--   doc      { title, desc, to }
--   proposal { text, todoIds[] }
--   draft    { conversationId, conversationName, text, state: pending|inserted|sent|dismissed, doneTodo }
CREATE TABLE agent_feed_item (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id    text NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  type        text NOT NULL CHECK (type IN ('status', 'user', 'agent', 'doc', 'proposal', 'draft')),
  payload     jsonb NOT NULL DEFAULT '{}',
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX agent_feed_owner_idx ON agent_feed_item (owner_id, id);

CREATE TABLE agent_quick_prompt (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id  text NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  body      text NOT NULL,
  position  integer NOT NULL DEFAULT 0
);

-- —— 搜索 ——
CREATE TABLE search_history (
  owner_id     text NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  query        text NOT NULL,
  searched_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (owner_id, query)
);
CREATE INDEX search_history_recent_idx ON search_history (owner_id, searched_at DESC);

CREATE INDEX app_user_search_trgm_idx ON app_user USING gin ((name || ' ' || role || ' ' || dept) gin_trgm_ops);
CREATE INDEX conversation_name_trgm_idx ON conversation USING gin (name gin_trgm_ops) WHERE type = 'group';
